version: '3'

services:
  postgres:
    container_name: POSTGRES
    image: postgres:alpine3.19
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - app-network

  composer:
    container_name: COMPOSER
    image: composer:latest
    volumes:
      - ./backend:/var/www/levach/backend
    working_dir: /var/www/levach/backend
    command: install
    depends_on:
      - php

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: