version: '3'

services:
  php:
    container_name: PHP
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG_MODE: ${DEBUG_MODE}
      IS_DEBUG_SERVER: false

      default_changeable_article_edit_timeout_minutes: ${default_changeable_article_edit_timeout_minutes}
      default_changeable_max_upload_filesize_mb: ${default_changeable_max_upload_filesize_mb}
      default_changeable_article_need_rating_to_approve_editorially: ${default_changeable_article_need_rating_to_approve_editorially}

      HOSTNAME: ${HOSTNAME}

      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      
      RECAPTCHA_SECRETKEY: ${RECAPTCHA_SECRETKEY}
    volumes:
      - ./:/var/www/levach:rw
      - ./php/php.ini-prod:/usr/local/etc/php/php.ini:rw
    expose:
      - "9000"
    depends_on:
      - node
    networks:
      - app-network

  nginx:
    container_name: NGINX
    image: nginx:latest
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:rw
      - ./media:/var/www/levach/media:rw
      - ./frontend:/var/www/levach/frontend:rw
      - ./backend:/var/www/levach/backend:rw
      - ./robots.txt:/var/www/levach/robots.txt:rw
    environment:
      HOSTNAME: ${HOSTNAME}
    depends_on:
      - composer
    ports:
      - "80:80"
    networks:
      - app-network
  node:
    container_name: NODEJS
    image: node:hydrogen-slim
    working_dir: /var/www/levach/frontend
    volumes:
      - ./frontend:/var/www/levach/frontend
    command: sh -c "npm install && npm run build"
    networks:
      - app-network

  postgres:
    container_name: POSTGRES
    image: postgres:alpine3.19
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

      ADMIN_DEFAULT_NAME: ${ADMIN_DEFAULT_NAME}
      ADMIN_DEFAULT_PASSWORD_ENCRYPTED: ${ADMIN_DEFAULT_PASSWORD_ENCRYPTED}
    volumes:
      - ./:/var/www/levach/:rw
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - app-network  
  
  composer:
    container_name: COMPOSER
    image: composer:latest
    volumes:
      - ./backend:/var/www/levach/backend
    working_dir: /var/www/levach/backend
    command: install
    depends_on:
      - php

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: