version: '3'

services:
  php:
    image: php:fpm
    volumes:
      - ./backend:/var/www/levach/backend
      - ./frontend:/var/www/levach/frontend
      - ./media:/var/www/levach/media
    expose:
      - "9000"
    depends_on:
      - node
    networks:
      - app-network

  postgres:
    image: postgres:alpine3.19
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - app-network

  composer:
    image: composer:latest
    volumes:
      - ./backend:/var/www/levach/backend
    working_dir: /var/www/levach/backend
    command: install
    depends_on:
      - php
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: