version: '3'

services:
  postgres:
    container_name: POSTGRES
    image: postgres:alpine3.19
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/var/www/levach/:rw
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: