DB_NAME=$DB_NAME
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

export PGPASSWORD=$POSTGRES_PASSWORD

cat /var/www/levach/database/migration.sql | psql -h $DB_HOST -U $POSTGRES_USER -d $DB_NAME