version: '3'

services:
  php:
    container_name: PHP
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      DEBUG_MODE: ${DEBUG_MODE}
      IS_DEBUG_SERVER: true

      default_changeable_article_edit_timeout_minutes: ${default_changeable_article_edit_timeout_minutes}
      default_changeable_max_upload_filesize_mb: ${default_changeable_max_upload_filesize_mb}
      default_changeable_article_need_rating_to_approve_editorially: ${default_changeable_article_need_rating_to_approve_editorially}

      HOSTNAME: ${HOSTNAME}

      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      RECAPTCHA_SECRETKEY: ${RECAPTCHA_SECRETKEY}
    volumes:
      - ./:/var/www/levach/:rw
      - ./php/php.ini-dev:/usr/local/etc/php/php.ini:rw
    expose:
      - "9000"
    depends_on:
      - node
    networks:
      - app-network

  nginx:
    container_name: NGINX
    image: nginx:latest
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:rw
      - ./media:/var/www/levach/media:rw
      - ./frontend:/var/www/levach/frontend:rw
      - ./backend:/var/www/levach/backend:rw
      - ./robots.txt:/var/www/levach/robots.txt:rw
    environment:
      HOSTNAME: ${HOSTNAME}
    depends_on:
      - composer
    ports:
      - "8080:80"
    networks:
      - app-network
    
  node:
    container_name: NODEJS
    image: node:hydrogen-slim
    working_dir: /var/www/levach/frontend
    volumes:
      - ./frontend:/var/www/levach/frontend:rw
    command: sh -c "npm install && npm run dev"
    environment:
      VITE_API_URL: http://nginx/api/
    ports:
     - 8000:8000
    expose:
      - "8000"
    networks:
      - app-network

  pgadmin:
    container_name: PGADMIN
    image: elestio/pgadmin:latest
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin:rw
    depends_on:
      - postgres
    networks:
      - app-network
  composer:
    container_name: COMPOSER
    image: composer:latest
    volumes:
      - ./backend:/var/www/levach/backend:rw
    working_dir: /var/www/levach/backend
    command: install
    depends_on:
      - php

volumes:
  pgadmin-data: