version: '3'

services:
  php:
    container_name: PHP
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG_MODE: ${DEBUG_MODE}
      IS_DEBUG_SERVER: true

      HOSTNAME: ${HOSTNAME}

      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backend:/var/www/levach/backend
      - ./frontend:/var/www/levach/frontend
      - ./media:/var/www/levach/media
    expose:
      - "9000"
    depends_on:
      - node
    networks:
      - app-network

  nginx:
    container_name: NGINX
    image: nginx:latest
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./media:/var/www/levach/media
      - ./frontend:/var/www/levach/frontend
      - ./backend:/var/www/levach/backend
    environment:
      HOSTNAME: ${HOSTNAME}
    depends_on:
      - composer
    ports:
      - "8080:80"
    networks:
      - app-network
    
  node:
    container_name: NODEJS
    image: node:hydrogen-slim
    working_dir: /var/www/levach/frontend
    volumes:
      - ./frontend:/var/www/levach/frontend
    command: sh -c "npm install && npm run dev"
    environment:
      - VITE_API_URL=http://nginx/api/
    ports:
     - 8000:8000
    expose:
      - "8000"
    networks:
      - app-network

  pgadmin:
    container_name: PGADMIN
    image: elestio/pgadmin:latest
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  pgadmin-data: