version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./media:/var/www/levach/media
      - ./frontend:/var/www/levach/frontend
      - ./backend:/var/www/levach/backend
    depends_on:
      - composer
    ports:
      - "8080:80"
    networks:
      - app-network
    
  node:
    image: node:hydrogen-slim
    working_dir: /var/www/levach/frontend
    volumes:
      - ./frontend:/var/www/levach/frontend
    command: sh -c "npm install && npm run dev"
    environment:
      - VITE_API_URL=http://nginx/api/
      - VITE_MEDIA_URL=http://nginx/media/
    ports:
     - 8000:8000
    expose:
      - "8000"
    networks:
      - app-network
      