DB_NAME=$DB_NAME
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

ADMIN_DEFAULT_NAME=$ADMIN_DEFAULT_NAME
ADMIN_DEFAULT_PASSWORD_ENCRYPTED=$ADMIN_DEFAULT_PASSWORD_ENCRYPTED

export PGPASSWORD=$POSTGRES_PASSWORD

psql -h $DB_HOST -U $POSTGRES_USER -d $DB_NAME "INSERT INTO admins VALUES ($ADMIN_DEFAULT_NAME, $ADMIN_DEFAULT_PASSWORD); "